# Site settings
title: TxHC Drone Services
email: info@thcdroneservices.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thcdroneservices.github.io/" # the base hostname & protocol for your site

instagram_username: thcdroneservices
google_username:

# Build settings
markdown: kramdown



